# Generated by Django 5.1.3 on 2024-11-22 22:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('status', models.CharField(choices=[('occupied', 'Occupied Territory'), ('liberated', 'Liberated Zone'), ('contested', 'Contested Area'), ('government', 'Under Government Control')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('strategic_value', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Areas',
                'ordering': ['-date', 'name'],
                'unique_together': {('name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AreaHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('status', models.CharField(choices=[('occupied', 'Occupied Territory'), ('liberated', 'Liberated Zone'), ('contested', 'Contested Area'), ('government', 'Under Government Control')], max_length=20)),
                ('date', models.DateField()),
                ('population', models.IntegerField(blank=True, null=True)),
                ('strategic_value', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='warmap.area')),
            ],
            options={
                'verbose_name_plural': 'Area histories',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('event_type', models.CharField(choices=[('battle', 'Battle'), ('siege', 'Siege'), ('movement', 'Troop Movement'), ('supply', 'Supply Line'), ('other', 'Other')], max_length=20, verbose_name='Event Type')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20, verbose_name='Severity')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('casualties', models.IntegerField(default=0, verbose_name='Casualties')),
                ('source', models.URLField(blank=True, verbose_name='Source URL')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='warmap.location')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('movement_type', models.CharField(choices=[('troops', 'Troop Movement'), ('supplies', 'Supply Movement'), ('refugees', 'Refugee Movement')], max_length=20, verbose_name='Movement Type')),
                ('line', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Movement Path')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('size', models.IntegerField(help_text='Number of troops/supplies/people', verbose_name='Size/Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_movements', to=settings.AUTH_USER_MODEL)),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_to', to='warmap.location')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_from', to='warmap.location')),
            ],
            options={
                'verbose_name': 'Movement',
                'verbose_name_plural': 'Movements',
                'ordering': ['-start_date'],
            },
        ),
    ]
